version: "3.8"
services:
  bingeWatachDbAssignment:
    image: 010aditya/bingewatachdbassignment:0.0.1
    ports:
      - "8080:8080"
    networks:
      - bingeWatachDbAssignmentApplication
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:latest
    networks:
      - bingeWatachDbAssignmentApplication
    environment:
      - MYSQL_ROOT_PASSWORD=aditya
      - MYSQL_DATABASE=netflix

networks:
  bingeWatachDbAssignmentApplication: